config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  get 'users/:id', to: 'users#show'
  post "/" => 'home#index'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  resources :users

  # ブロック関数を使用
  resources :maps do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/map.rb
class Map < ApplicationRecord
  mount_uploader      :picture, PictureUploader
  reverse_geocoded_by :latitude, :longitude
  after_validation    :reverse_geocode
  before_validation   :kill_whitespace

  validates :user_id,     presence: true
  validates :title,       presence: true,
                          length: { maximum: 20 }

  validates :content,     presence: true,
                          length: { maximum: 300 }

  validates :latitude,    presence: true
  validates :longitude,   presence: true

  # user.rbのhas_manyに対応する
  belongs_to  :user
  # likeテーブルと1対多になる
  has_many    :likes,       dependent: :destroy
  # 投稿が、どのユーザにいいねされているか取得
  has_many    :liked_users, through: :likes,    source: :user
  # commentテーブルと1対多になる
  has_many    :comments,    dependent: :destroy

  # 最近作成されたユーザーから表示
  default_scope -> { order(created_at: :desc) }
  # 一度に表示する投稿数
  paginates_per 6

  enum pref_area:{
    北海道:0,青森県:1,岩手県:2,宮城県:3,秋田県:4,山形県:5,福島県:6,
    茨城県:7,栃木県:8,群馬県:9,埼玉県:10,千葉県:11,東京都:12,神奈川県:13,
    新潟県:14,富山県:15,石川県:16,福井県:17,山梨県:18,長野県:19,
    岐阜県:20,静岡県:21,愛知県:22,三重県:23,
    滋賀県:24,京都府:25,大阪府:26,兵庫県:27,奈良県:28,和歌山県:29,
    鳥取県:30,島根県:31,岡山県:32,広島県:33,山口県:34,
    徳島県:35,香川県:36,愛媛県:37,高知県:38,
    福岡県:39,佐賀県:40,長崎県:41,熊本県:42,大分県:43,宮崎県:44,鹿児島県:45,沖縄県:46
  }

  def self.search(address)
    return Map.all unless address

    Map.where(['content LIKE ?', "%#{address}%"])
  end

  private

    # 投稿時のタイトルに入力されるスペースを削除する
    def kill_whitespace
      self.title = title.gsub(/[[:space:]]/, '') if title.present?
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  # google map apiを取得する
  before_action :set_map, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  def search
    @test = Map.search(params[:address])
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
    @map = Map.find(params[:id])
    # いいね機能追加
    @like = Like.new
    gon.lat = @map.latitude
    gon.lng = @map.longitude
    # コメント投稿
    @comment = Comment.new
    # 新着順で表示
    @comments = @map.comments.order(created_at: :desc).page(params[:page]).per(10)
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit; end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)
    @map.user_id = current_user.id
    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: '新しいスポットが無事登録されました！' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'スポットが無事更新されました！' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'スポットが無事削除されました！' }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def map_params
      params.require(:map).permit(:spot_style, :helmet, :latitude, :longitude, :picture, :content, :title)
    end
end

app/views/maps/_form.html.erb
<%= form_with(model: map, local: true) do |form| %>
  <% if map.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>
        <ul>
          <% map.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <div class="map" id='newpost'></div>
  <ol>
    <!-- 地図を表示させる要素 -->
    <br>
    <li><p><span class="markerB">どんなスポット？</span></p>
              <%= form.select :spot_style, [['スケートパーク', true], ['ストリートスポット', false]], class: "clear-button"%>
    </li> <br>
    <li><p><span class="markerB">ヘルメットの着用義務は？</span></p>
              <%= form.select :helmet, [['有り', true],['無し', false]] %>
    </li> <br>
    <li><p><span class="markerB">スケートパークやスポット名は？</span></p>
              <%= form.text_field :title, placeholder: "20字以内で" %>
    </li> <br>
    <li><p><span class="markerB">説明や備考などあれば</span></p>
              <%= form.text_area :content, size: "60x3", placeholder: "400字以内で" %>
    </li> <br>
    <li><p><span class="markerB">写真をアップロード</span></p>
                <p class="font-xs">（未設定でデフォルト画像がセットされます）</p>
                <%= form.file_field :picture, class: "btn slide-grey"%>
    </li> <br>
              <%= form.hidden_field :latitude, {id: "lat"} %>
              <%= form.hidden_field :longitude, {id: "lng"} %>
    <%= button_tag type: 'submit', class: "btn-cubic", id: 'btn' do %>
      <span class="hovering-submit">
        <i class="fas fa-paper-plane"></i>
      </span>
      <span class="default">投稿</span>
    <% end %>
  </ol>
<% end %>

<%# function getMap関数をコールバックして、#newpostに挿入。サイズはclass="map"で指定 %>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google_map_api[:key] %>&callback=postMap" async defer></script>

app/views/maps/_googlemap.html.erb
<!-- gmap挿入 -->
    <script>
    var getMap = (function() {
        function codeAddress(address) {
          // google.maps.Geocoder()コンストラクタのインスタンスを生成
          var geocoder = new google.maps.Geocoder();

          //マーカー変数用意
          var marker;

          // 地図表示に関するオプション
          var mapOptions = {
            zoom: 16,
            mapTypeId: google.maps.MapTypeId.HYBRID
          };

          // 地図を表示させるインスタンスを生成
          var map = new google.maps.Map(document.getElementById("initmap"), mapOptions);

          // geocoder.geocode()メソッドを実行
          geocoder.geocode( { 'address': address}, function(results, status) {
            // ジオコーディングが成功した場合
            if (status == google.maps.GeocoderStatus.OK) {
              // 変換した緯度・経度情報を地図の中心に表示
              map.setCenter(results[0].geometry.location);
              //☆表示している地図上の緯度経度
              document.getElementById('lat').value=results[0].geometry.location.lat();
              document.getElementById('lng').value=results[0].geometry.location.lng();
              // マーカー設定
              marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location
              });
            // ジオコーディングが成功しなかった場合
            } else {
              console.log('Geocode was not successful for the following reason: ' + status);
            }
          });

          // マップをクリックで位置変更
          map.addListener('click', function(e) {
            getClickLatLng(e.latLng, map);
          });
          function getClickLatLng(lat_lng, map) {

            //☆表示している地図上の緯度経度
            document.getElementById('lat').value=lat_lng.lat();
            document.getElementById('lng').value=lat_lng.lng();

            // マーカーを設置
            marker.setMap(null);
            marker = new google.maps.Marker({
              position: lat_lng,
              map: map,
              animation: google.maps.Animation.DROP
            });

            // 座標の中心をずらす
            map.panTo(lat_lng);
          }
        }

        //inputのvalueで検索して地図を表示
        return {
          getAddress: function() {
            // ボタンに指定したid要素を取得
            var button = document.getElementById("map_button");

            // ボタンが押された時の処理
            button.onclick = function() {
              // フォームに入力された住所情報を取得
              var address = document.getElementById("address").value;
              // 取得した住所を引数に指定してcodeAddress()関数を実行
              codeAddress(address);
            }

            //読み込まれたときに地図を表示
            window.onload = function(){
              // フォームに入力された住所情報を取得
              var address = document.getElementById("address").value;
              // 取得した住所を引数に指定してcodeAddress()関数を実行
              codeAddress(address);
            }
          }
        };
      })();
      getMap.getAddress();
    </script>

<!-- apiキー -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA5qtdZ0_IRKciy41eDwLL9fTQzwR_7BAI&callback=initMap" async defer></script>

app/views/maps/_googlemap_route.html.erb
<!-- 現在値取得map -->
<script>
function initMap() {
  var target = document.getElementById('routemap');
  //マップを生成して表示
  var map = new google.maps.Map(document.getElementById('routemap'), {
    center: {lat: 35.681167, lng: 139.767052},
    zoom: 15
  });
  //情報ウィンドウのインスタンスの生成
  var infoWindow = new google.maps.InfoWindow;

  //ブラウザが Geolocation に対応しているかを判定
  //対応していない場合の処理
  if(!navigator.geolocation){
    //情報ウィンドウの位置をマップの中心位置に指定
    infoWindow.setPosition(map.getCenter());
    //情報ウィンドウのコンテンツを設定
    infoWindow.setContent('Geolocation に対応していません。');
    //情報ウィンドウを表示
    infoWindow.open(map);
  }

  //ブラウザが対応している場合、position にユーザーの位置情報が入る
  navigator.geolocation.getCurrentPosition(function(position) {
    //position から緯度経度（ユーザーの位置）のオブジェクトを作成し変数に代入
    var pos = {
      lat: position.coords.latitude,
      lng: position.coords.longitude
    };

    //gon gemで定義したmapモデル内のlatitudeとlongitudeを使用
    var latlng = {
      lat: gon.lat,
      lng: gon.lng
    };

    //DirectionsService のオブジェクトを生成
    var directionsService = new google.maps.DirectionsService();
    //DirectionsRenderer のオブジェクトを生成
    var directionsRenderer = new google.maps.DirectionsRenderer();
    //directionsRenderer と地図を紐付け
    directionsRenderer.setMap(map);

    // ルートを取得するリクエスト
    var request = {
      origin: pos,      // 出発地点の緯度経度（ユーザーの位置）
      //gon gemで定義した目的地をlatlngに格納したものを使用
      destination: latlng, // 到着地点
      travelMode: 'DRIVING',  //公共交通機関
    };

    //DirectionsService のオブジェクトのメソッド route() にリクエストを渡し、
    //コールバック関数で結果を setDirections(result) で directionsRenderer にセットして表示
    directionsService.route(request, function(result, status) {
      //ステータスがOKの場合、
      if (status === 'OK') {
        directionsRenderer.setDirections(result); //取得したルート（結果：result）をセット
      }else{
        alert("取得できませんでした：" + status);
      }
    });

  }, function() {  //位置情報の取得をユーザーがブロックした場合のコールバック
    //情報ウィンドウの位置をマップの中心位置に指定
    infoWindow.setPosition(map.getCenter());
    //情報ウィンドウのコンテンツを設定
    infoWindow.setContent('Error: あなたの現在地が取得できませんでした。');
    //情報ウィンドウを表示
    infoWindow.open(map);
  });
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?
key=AIzaSyA5qtdZ0_IRKciy41eDwLL9fTQzwR_7BAI&callback=initMap" async defer></script>

app/views/maps/_maps_info_card.html.erb
<% @maps.each do |map| %>
    <div class="col mb-4">
        <div class="card border-0">
            <div class="card-body">

                <h5>
                <% if map.title? %>
                    <%= map.title %>
                <% else %>
                    タイトル
                <% end %>
                </h5>

                <p>
                <% if map.content? %>
                    <%= map.content %>
                <% else %>
                    あなたのお気に入りスポットです！
                <% end %>
                </p>
                <%= image_tag map.picture.url, class: "card-img-top border rounded border-dark" %>

                <%= link_to 'Show', map %> | 
                <%= link_to 'Edit', edit_map_path(map) %> | 
                <%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %>

            </div>
        </div>
    </div>
<% end %>

app/views/maps/_mapscard.html.erb
<div class="card">
  <div class="image"><%= link_to image_tag(post.picture.thumb.url, size: "275x275"),map_path(post) %></div>
    <div class="info">
      <div class="title"><%= link_to post.title, map_path(post), class: "link_to_text_wh" %></div>
      <div class="detail"><%= link_to post.content, map_path(post), class: "link_to_text_wh" %></div>
    </div>
    <div class="social">
      <ul>
          <%= link_to image_tag(post.user.image.url, size:"45x45", class: "window") %>
          <p class="font-s name-aria"><%= link_to post.user.name, post.user ,class: "link_to_text_bk"%></p>
          <p class="font-xs">作成日<br><%= post.created_at.strftime("%m/%d") %></p>
        <%# 挿入：いいねボタン %>
          <span id="likes_buttons_<%= post.id %>">
            <%= render partial: '/likes/likes_btn', locals: {post: post} %>
          </span>
        <%# 挿入：いいねカウント %>
          <span class="Grid__font-s" id="likes_count_<%= post.id %>">
            <%= render partial: '/likes/likes_count', locals: {post: post} %>
          </span>
      </ul>
    </div>
</div>

app/views/maps/_navs_tab.html.erb
    <!-- ここにnavs_tabを設置 -->
    <ul class="nav nav-tabs justify-content-center col-12 mt-3">
    <li class="nav-item">
        <a href="#text" class="nav-link active" data-toggle="tab" >
        <i class="far fa-newspaper"></i>
        </a>
    </li>
    <li class="nav-item">
        <a href="#gmap" class="nav-link" data-toggle="tab">
        <i class="fas fa-globe-asia"></i>
        </a>
    </li>
    <li class="nav-item">
        <a href="#likeUsers" class="nav-link" data-toggle="tab">
        <i class="far fa-heart text-muted fa-fw"></i>
        </a>
    </li>
    </ul><br>

    <div class="tab-content mx-auto">
        <!-- ここにtextページ -->
        <div id="text" class="tab-pane active">
        <div class="text-center">
            <h2 class="font-weight-bold mt-2"><%= @map.title %></h2>
            <% if @map.content %>
                <span style="white-space:pre-wrap"><%= @map.content %></span>
            <% end %>
        </div>
        </div>
        <!-- ここにgooglemapページ -->
        <div id="gmap" class="tab-pane">
        <div class="text-center">
            <%= @map.address %>
        </div>
        </div>
    <!-- ここにいいね -->
        <div id="likeUsers" class="tab-pane">
        <div class="text-center">
            <p>いいねページ表示</p>
        </div>
        </div>
    </div>

app/views/maps/_postcard.html.erb
<% @maps.each do |map| %>
    <div class="col mb-4">
        <div class="card">
            <div class="card-body">

                <% if map.picture? %>
                <%= image_tag map.picture.url, class: "card-img-top" %>
                <% else %>
                <%= image_pack_tag 'media/images/no-image.jpg', class: "card-img-top" %>
                <% end %>

                <h5>
                <% if map.title? %>
                    <%= map.title %>
                <% else %>
                    タイトル
                <% end %>
                </h5>

                <p>
                <% if map.content? %>
                    <%= map.content %>
                <% else %>
                    あなたのお気に入りスポットです！
                <% end %>
                </p>

                <%= link_to 'Show', map %> | 
                <%= link_to 'Edit', edit_map_path(map) %> | 
                <%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %>

            </div>
        </div>
    </div>
<% end %>

app/views/maps/_show_mapscard.html.erb
<%# 挿入：いいねボタン & いいねカウント %>
  <div id="likes_buttons_<%= post.id %>">
    <%= render partial: '/likes/likes_btn', locals: {post: post} %>
  </div>
  <span id="likes_count_<%= post.id %>">
    <%= render partial: '/likes/likes_count', locals: {post: post} %>
  </span>
  <span>人が、ｲｲﾈ!しています。</span>

<%# 挿入： 投稿情報ドロワーのレイアウト %>
<div class="show_card" id="drawer-menu">
  <div class="card-image">
    <div class="route-map" id='routes'></div>
  </div>
  <div class="card-body">
    <div class="controls">
      <div class="controls__c1">
        <a class="drawer">
          <p class="up"><i class="far fa-hand-point-up fa-lg"></i></p>
          <p class="down"><i class="far fa-hand-point-down fa-lg"></i></p>
        </a>
      </div>
      <div class="controls__c2">
        <p class="font-lg">
          <i class="fas fa-car"></i><span id="msg_d"></span>
          /
          <i class="far fa-clock"></i><span id="msg_t"></span>
        </p>
      </div>
    </div>
    <div class="Grid">
        <div class="Grid__c1">
          <div class="Grid__box-layout">
              <% if post.spot_style? %>
                <i class="fas fa-store-alt"></i> <span class="Grid__font-s">スケートパーク</span>
              <% else%>
                <i class="fas fa-street-view"></i> <span class="Grid__font-s">ストリート</span>
              <% end %>
          </div>
        </div>
        <div class="Grid__c2">
            <div class="Grid__box-layout">
              <% if post.helmet? %>
              　<span class="Grid__font-s">ヘルメット着用</span>
              <% else %>
                <span class="Grid__font-s">ヘルメット不要</span>
              <% end %>
            </div>
        </div>
        <div class="Grid__c3">
            <div class="Grid__box-layout">
              <%= post.address %>
            </div>
        </div>
        <div class="Grid__c4">
            <div class="Grid__image Grid__box-layout">
              <%= image_tag post.picture.url , class: "Grid__resize"%>
            </div>
        </div>
        <div class="Grid__c5">
            <p class="Grid__text-layout Grid__font-s"><%= post.content %></p>
        </div>
    </div>
  </div>
</div>

<%# function initMap関数をコールバックして、#routesに挿入。サイズはclass="map"で指定 %>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google_map_api[:key] %>&callback=initMap" async defer></script>

app/views/maps/edit.html.erb
<main>
  <div class="first-content">
    <h1>Editing Map</h1>
      <form onsubmit="return false;">
        <input type="text" maxlength="20" value="東京　スケートパーク" id="address">
          <%= button_tag type: 'submit', id: "map_button", class: "btn-mini slide-bg" do %>
            <i class="fas fa-search-location"></i>
          <% end %>
      </form>
      <p class="font-xs">検索バー　or　地図上を移動してクリック<br>マーカーを落として、登録しよう！</p>
    <%= render '/maps/form', map: @map %>
    <%= link_to 'Show', @map %> |
    <%= link_to 'Back', maps_path %>
  </div>
</main>

app/views/maps/index.html.erb
<main>
  <div class="first-content">
    <h2 class="textORG">VIEW SPOT</h2><br>
    <div class="item-center">
    <%# any?: 検索キーワード１つでも該当すれかどうかで分岐　%>
    <% if @search_maps.any? %>
          <div class="form">
            <ul class="form__ul">
              <li class="form__li">
                <%= render partial: "/shared/search_form/map_title_cont" %>
              </li>
              <li>
                <%= render partial: "/shared/search_form/map_address_cont" %>
              </li>
            </ul>
          </div>
              <div class="map_card_container" id="items">
                <%= render partial: "maps/mapscard", collection: @search_maps, as: "post" %>
              </div>
            <%= link_to_next_page @search_maps, 'つづきを見る', remote: true, class: "btn filled", id: 'more_link' %>
          </div>
    <% else %>
          <div>
            <%= render'/shared/search_form/map_title_cont' %>
              <br><br>
                <h3>まだコンテンツが投稿されていません！</h3>
              <br><br>
          </div>
    <% end %>
    </div>
  </div>
</main>

app/views/maps/index.js.erb
$("#items").append("<%= j(
  render partial: 'maps/mapscard', collection: @search_maps, as: "post") %>");

$("#more_link").replaceWith("<%= j(
  link_to_next_page(@search_maps, 'つづきを見る', remote: true, class: "btn filled", id: 'more_link')) %>");

app/views/maps/new.html.erb
<main>
  <div class="first-content">
    <h2><span class="textORG">NEW POST</span></h2><br>
    <div class="item-center">
      <form onsubmit="return false;">
          <input type="text" maxlength="20" value="東京　スケートパーク" id="address">
            <%= button_tag type: 'submit', id: "map_button", class: "btn-mini slide-bg" do %>
              <i class="fas fa-search-location"></i>
            <% end %>
      </form>
      <p class="font-xs">マーカーを落として、登録しよう！</p>
    </div>
    <%= render "/maps/form", map: @map %> <br>
    <%= link_to 'Back', maps_path %>
  </div>
</main>

app/views/maps/show.html.erb
<main>
  <div class="first-content">
    <h2 class="textORG"><%= @map.title %></h2>
      <%= render "maps/show_mapscard", post: @map %> <br><br>
        <!--コメント機能-->
          <div class="item-center">
              <!--件数-->
            <div id="comment-count">
                <span>&nbsp;<%= @map.comments.count %>件</span>
            </div>
              <!--内容-->
            <div id="comments-list">
                <% if @comments.any? %>
                    <%= render partial: '/comments/comment-list', collection: @comments, as: 'comment' %>
                <% else %>
                    <span>コメントはまだありません</span>
                <% end %>
            </div>
              <!--10件以上は、view_moreボタンで制限-->
            <%= link_to_next_page @comments, 'すべてのコメントを見る', remote: true, class: "btn filled", id: 'view_more' %>
              <!--コメントのコンテントを送信するフォーム-->
            <%= render '/comments/comment-form' %>
              <!--投稿者情報-->
            <br><span>投稿者:</span>
            <%= link_to image_tag(@map.user.image.url, size:"45x45", class: "user-image-window") %>
            <%= link_to @map.user.name, @map.user, class: "link_to_text_bk" %>
            <%= @map.created_at.strftime("%Y-%m/%d %H:%M") %>
            <!--編集と削除アイコン-->
            <% if user_signed_in? %>
              <% if current_user.id == @map.user_id %>
                <%= link_to edit_map_path(@map) do %>
                  <i class="fas fa-edit link_to_text_bk"></i>
                  | 
                <% end %>
                <%= link_to @map, method: :delete, id: "delete_btn", data: { confirm: '本当に削除してもよろしいですか?' } do %>
                  <i class="fas fa-trash-alt link_to_text_bk"></i>
                <% end %>
              <% end %>
            <% else %>
              <br>
                <%= link_to new_user_registration_path , class: "btn filled" do %>
                  <i class="fas fa-user-plus"></i>
                  new user
                <% end %>
            <% end %>
          </div>
  </div>
</main>

app/views/maps/show.js.erb
$('#comments-list').append("<%= escape_javascript(
  render partial: '/comments/comment-list', collection: @comments, as: 'comment') %>");

$("#view_more").replaceWith("<%= escape_javascript(
  link_to_next_page(@comments, 'つづきを見る', remote: true, id: 'view_more')) %>");