config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  get 'users/:id', to: 'users#show'
  post "/" => 'home#index'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  resources :users

  # ブロック関数を使用
  resources :maps do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def follow
    current_user.follow(params[:id])
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
    end
  end

  def unfollow
    current_user.unfollow(params[:id])
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end
end

app/views/relationships/_add-follower.html.erb
<span class="font-xs">フォロワー数</span>　 <%= feed.followed.count %>

app/views/relationships/_follow-bar-count.html.erb
<h2><%= "フォロー数: #{@user.follower.count}" %></h2>
    <% @user.following_user.each do |user| %>
      <%= link_to image_tag(user.image.url, size:"45x45", class: "user-image-window") %>
      <%= link_to "@#{user.name}", user_path(user), class: "link_to_text_bk" %> <br><br>
    <% end %>

app/views/relationships/_follow_button.html.erb
<%# 未ログイン、フォローボタン非表示 %>
<% if user_signed_in? %>
  <%# unless分岐： %>
  <% unless current_user == feed %>
      <%#本人以外で表示%>
      <% if current_user.following?(feed) %>
        <%#フォローしている%>
        <span class="font-xs">フォロー中　</span>
        <%= link_to unfollow_path(feed.id), method: :POST, remote: true, class: "clear-button" do %>
          <i class="fas fa-handshake fa-lg follow_green", id="yes-follow"></i>
        <% end %>
      <% else %>
        <%#まだフォローしてない%>
        <span class="font-xs">フォローは → </span>
        <%= link_to follow_path(feed.id), method: :POST, remote: true, class: "clear-button" do %>
          <i class="far fa-handshake fa-lg unfollow_grey", id="no-follow"></i>
        <% end %>
      <% end %>
  <% else %>
      <%#ログイン中ユーザーと同じユーザーカードに対して%>
      <span class="font-xs text_danger">ログイン中</span>
  <% end %>
<% else %>
  <i class="fas fa-handshake"></i>
<% end %>

app/views/relationships/_follower-bar-count.html.erb
<h2><%= "フォロワー数: #{@user.followed.count}" %></h2>
    <% @user.follower_user.each do |user| %>
        <%= link_to image_tag(user.image.url, size:"45x45", class: "user-image-window") %>
        <%= link_to "@#{user.name}", user_path(user), class: "link_to_text_bk" %> <br><br>
    <% end %>

app/views/relationships/follow.js.erb
<!--ajax：フォローボタンのアイコンを変更-->
$("#follow-button_<%= @user.id %>").html    ("<%= j(render partial: 'relationships/follow_button',      locals: { feed: @user }) %>");

<!--ajax：タブバー内のフォロー中人数を変更-->
$("#follow-count_<%= @user.id %>").html     ("<%= j(render partial: 'relationships/follow-bar-count',   locals: { feed: @user }) %>");

<!--ajax：タブバー内のフォロワー人数を変更-->
$("#follower-count_<%= @user.id %>").html   ("<%= j(render partial: 'relationships/follower-bar-count', locals: { feed: @user }) %>");

<!--ajax：ユーザ一覧ページにて、フォロワー人数を変更-->
$("#add-follower_<%= @user.id %>").html     ("<%= j(render partial: 'relationships/add-follower',       locals: { feed: @user }) %>");

app/views/relationships/unfollow.js.erb
<!--ajax：フォローボタンのアイコンを変更-->
$("#follow-button_<%= @user.id %>").html    ("<%= j(render partial: 'relationships/follow_button',      locals: { feed: @user }) %>");

<!--ajax：タブバー内のフォロー中人数を変更-->
$("#follow-count_<%= @user.id %>").html     ("<%= j(render partial: 'relationships/follow-bar-count',   locals: { feed: @user }) %>");

<!--ajax：タブバー内のフォロワー人数を変更-->
$("#follower-count_<%= @user.id %>").html   ("<%= j(render partial: 'relationships/follower-bar-count', locals: { feed: @user }) %>");

<!--ajax：ユーザ一覧ページにて、フォロワー人数を変更-->
$("#add-follower_<%= @user.id %>").html     ("<%= j(render partial: 'relationships/add-follower',       locals: { feed: @user }) %>");