config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  get 'users/:id', to: 'users#show'
  post "/" => 'home#index'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  resources :users

  # ブロック関数を使用
  resources :maps do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/views/shared/_footer.html.erb
<hr>
<footer class="footer">
  <div class="logo">
    <span><%= link_to image_pack_tag("media/images/logo.svg", size: "50"), root_path, class: "logo__img" %></span>
    <span><%= link_to "skate_" , root_path , class: "logo__skate" %></span>
    <span class="logo__spot"><%= link_to "spot_" , root_path , class: "logo__spot" %></span>
    <span class="logo__search"><%= link_to "search" , root_path , class: "logo__search" %></span>
  </div>
  <nav class="footer__nav">
      <ul class="footer__ul">
        <li class="footer__li">
          <%= link_to inquiry_path , method: :post , class: "header__link"  do %>
            <i class="fas fa-sign-in-alt"></i>
            問い合わせ & よくある質問
          <% end %>
        </li>
      </ul>
      <div class="footer__copyright">
        &copy; 2020 UechiKohei
      </div>
  </nav>
</footer>

app/views/shared/_header.html.erb
<div class="mobile-menu__cover"></div>
<header class="header">
  <div class="header__inner">
    <div class="logo">
      <span><%= link_to image_pack_tag("media/images/logo.svg", size: "50"), root_path, class: "logo__img" %></span>
      <span><%= link_to "skate_" , root_path , class: "logo__skate" %></span>
      <span class="logo__spot"><%= link_to "spot_" , root_path , class: "logo__spot" %></span>
      <span class="logo__search"><%= link_to "search" , root_path , class: "logo__search" %></span>
    </div>
    <nav class="header__nav">
      <ul class="header__ul">
        <% if user_signed_in? %>
            <li class="header__li">
              <%= link_to maps_path, class: "header__link" do %>
                <i class="fab fa-searchengin"></i>
                <span>view spot</span>
              <% end %>
            </li>
            <li class="header__li">
              <%= link_to new_map_path , class: "header__link" do %>
                <i class="fas fa-map-pin"></i>
                new
              <% end %>
            </li>
            <li class="header__li">
              <%= link_to users_path , class: "header__link" do %>
                <i class="fas fa-users"></i>
                lists
              <% end %>
            </li>
            <li class="header__li">
              <%= link_to user_path(id: current_user), class: "header__link"  do %>
                <i class="fas fa-user-circle"></i>
                profile
              <% end %>
            </li>
            <li class="header__li">
              <%= link_to destroy_user_session_path, method: :delete , class: "btn filled", id: "logout" do %>
                <i class="fas fa-sign-out-alt"></i>
                ログアウト
              <% end %>
            </li>
        <% else %>
            <li class="header__li">
              <%= link_to new_user_registration_path , class: "btn filled" do %>
                <i class="fas fa-user-plus"></i>
                new user
              <% end %>
            </li>
            <li class="header__li">
              <%= link_to new_user_session_path , class: "btn filled" do %>
                <i class="fas fa-sign-in-alt"></i>
                sign in
              <% end %>
            </li>
            <li class="header__li">
              <%= link_to users_guest_sign_in_path , method: :post , class: "btn filled" do %>
                <i class="fas fa-sign-in-alt"></i>
                guest_log_in
              <% end %>
            </li>
        <% end %>
      </ul>
    </nav>
    <button class="mobile-menu__btn">
      <span></span>
      <span></span>
      <span></span>
    </button>
  </div>
</header>

app/views/shared/_mobile-menu.html.erb
<nav class="mobile-menu">
    <div class="logo">
      <span><%= link_to image_pack_tag("media/images/logo.svg", size: "50"), root_path, class: "logo__img" %></span>
      <span><%= link_to "skate_" , root_path , class: "logo__skate" %></span>
      <span class="logo__spot"><%= link_to "spot_" , root_path , class: "logo__spot" %></span>
      <span class="logo__search"><%= link_to "search" , root_path , class: "logo__search" %></span>
    </div>
    <ul class="mobile-menu__main">
      <% if user_signed_in? %>
        <li class="mobile-menu__item">
          <%= link_to maps_path , class: "mobile-menu__link" do %>
            <i class="fab fa-searchengin fa-lg"></i>
            <span class="main-title">view spot</span>
            <span class="sub-title">スケートスポットを見る</span>
          <% end %>
        </li>
        <li class="mobile-menu__item">
          <%= link_to new_map_path, class: "mobile-menu__link" do %>
            <i class="fas fa-map-pin fa-lg"></i>
            <span class="main-title">new</span>
            <span class="sub-title">スポットを投稿する</span>
          <% end %>
        </li>
        <li class="mobile-menu__item">
          <%= link_to users_path, class: "mobile-menu__link" do %>
            <i class="fas fa-users fa-lg"></i>
            <span class="main-title">lists</span>
            <span class="sub-title">登録ユーザーを閲覧</span>
          <% end %>
        </li>
        <li class="mobile-menu__item">
          <%= link_to user_path(id: current_user), class: "mobile-menu__link" do %>
            <i class="fas fa-user-circle fa-lg"></i>
            <span class="main-title">profile</span>
            <span class="sub-title">ログインユーザーのプロフィールを閲覧</span>
          <% end %>
        </li>
          <br><br>
        <li class="mobile-menu__item">
          <%= link_to destroy_user_session_path, method: :delete , class: "btn filled" do %>
            <i class="fas fa-sign-out-alt"></i>
            log_out
          <% end %>
        </li>
      <% else %>
        <li class="mobile-menu__item">
          <%= link_to maps_path , class: "mobile-menu__link" do %>
            <i class="fab fa-searchengin fa-lg"></i>
            <span class="main-title">view spot</span>
            <span class="sub-title">スケートスポットを見る</span>
          <% end %>
        </li>
          <br><br>
        <li class="mobile-menu__item">
          <%= link_to new_user_registration_path , class: "btn filled" do %>
            <i class="fas fa-user-plus"></i>
            new user
          <% end %>
          <span class="sub-title">新規登録して、サービスを利用しよう！</span>
        </li>
          <br>
        <li class="mobile-menu__item">
          <%= link_to new_user_session_path , class: "btn filled" do %>
            <i class="fas fa-sign-in-alt"></i>
            sign in
          <% end %>
          <span class="sub-title">ログインはこちら！</span>
        </li>
          <br>
        <li class="mobile-menu__item">
          <%= link_to users_guest_sign_in_path, method: :post, class: "btn filled" do %>
            <i class="fas fa-sign-in-alt"></i>
            guest_log_in
          <% end %>
          <span class="sub-title">ポートフォリオ閲覧の方はこちら！</span>
        </li>
      <% end %>
    </ul>
</nav>

app/views/shared/_search_form.html.erb
<div class="text-center mt-2">
    <%= search_form_for @key do |f| %>
        <%= f.search_field :address_cont, placeholder: '名前を入力...' %>
        <%= button_tag type: 'submit', class: 'btn btn-warning mb-1' do %>
            <i class="fas fa-search"></i>
        <% end %>
    <% end %>
</div>

app/views/shared/_search_form_user.html.erb
<div class="text-center mt-2">
    <%= search_form_for @user_key do |f| %>
        <%= f.search_field :name_cont, placeholder: 'ユーザー名...' %>
            <%= button_tag type: 'submit', class: 'btn btn-warning mb-1' do %>
                <i class="fas fa-search"></i>
            <% end %>
    <% end %>
</div>