config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  get 'users/:id', to: 'users#show'
  post "/" => 'home#index'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面

  resources :users

  # ブロック関数を使用
  resources :maps do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  attr_accessor :name, :mail, :message

  validates :name, presence: { message: '名前を入力してください' }
  validates :mail, presence: { message: 'メールアドレスを入力してください' }
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render action: 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :mail, :message))
    if @inquiry.valid?
      # OK。確認画面を表示
      render action: 'confirm'
    else
      # NG。入力画面を再表示
      render action: 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry].permit(:name, :mail, :message))
    InquiryMailer.send_mail(@inquiry).deliver

    # 完了画面を表示
    render action: 'thanks'
  end
end

app/views/inquiry/confirm.html.erb
<main>
  <div class="first-content">
    <div class="box18">
      <h1>お問い合わせ</h1>
        <%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
          <table class="table">
            <tr>
              <th>名前</th>
              <td>
                <%= f.hidden_field :name %>
                <%= @inquiry.name %>
              </td>
            </tr>
            <tr>
              <th>メールアドレス</th>
              <td>
                <%= f.hidden_field :mail %>
                <%= @inquiry.mail %>
              </td>
            </tr>
            <tr>
              <th>お問い合わせ内容</th>
              <td>
                <%= f.hidden_field :message %>
                <%= simple_format(@inquiry.message) %>
              </td>
            </tr>
          </table>
          <%= f.submit '送信' %>
        <% end %>
    </div>
  </div>
</main>

app/views/inquiry/index.html.erb
<main>
  <div class="first-content">
  <%# よくある質問　%>
    <h1>よくある質問</h2>
    <div class="box18">
      <h3>問.　<span class="markerB">PC版のchromeブラウザで閲覧中、現在地から目的地までのルートが反映されません。</span></h3>
      <br><br>
        <h3>答.　<span class="markerY">位置情報を許可してください。</span></h3>
      <br><br>
      <h3>[手順]</h3>
      <ol>
        <li>パソコンで Chrome を開きます。</li>
        <li>右上のその他アイコン その他 次に [設定] をクリックします。</li>
        <li>[プライバシーとセキュリティ] の [サイトの設定] をクリックします。</li>
        <li>[位置情報] をクリックします。</li>
        <li>[アクセスする前に確認する] をオンまたはオフにします。</li>
      </ol>
    </div>
      <br><br>
    <div class="box18">
      <h3>問.　<span class="markerB">スマホ版のchromeブラウザを操作中、新規投稿ページからカメラを起動して撮影したいのですがカメラが真っ黒で撮影ができません。</span></h3>
      <br><br>
        <h3>答.　<span class="markerY">スマホchromeブラウザのアプリ設定からカメラを許可してください。</span></h3>
      <br><br>
        <h3>[手順]</h3>
        <ol>
          <li>設定を開く。</li>
          <li>chromeを開く。</li>
          <li>カメラをオンにする。</li>
        </ol>
      </div>
        <br><br>
      <div class="box18">
        <%# 問い合わせフォーム　%>
        <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
          <h2><span class="markerB">お問い合わせ</span></h2>
          <br>
          <p>(その他あれば内容を記載の上、問い合わせフォームよりお知らせください)</p>
          <br><br>
          <% if @inquiry.errors.any? %>
            <div id="error_explanation" role="alert">
              <strong class="markerY">入力内容にエラーがあります</strong>
              <br><br>
              <ul>
                <% @inquiry.errors.each do |attr, msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <%# 問い合わせフォーム　%>
          <table>
            <tr>
              <th>名前<span class="text-danger">（必須）</span></th>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <th>メールアドレス<span class="text-danger">（必須）</span></th>
              <td><%= f.text_field :mail %></td>
            </tr>
            <tr>
              <th>お問い合わせ内容</th>
              <td><%= f.text_area :message %></td>
            </tr>
          </table>
          <%= button_tag type: 'submit', class: "btn-cubic", id: 'btn' do %>
            <span class="hovering-submit">
              <i class="fas fa-paper-plane"></i>
            </span>
            <span class="default">確認</span>
          <% end %>
        <% end %>
      </div>
    <br><br>
  </div>
</main>

app/views/inquiry/thanks.html.erb
<main>
  <div class="first-content">
    <div class="box18">
      <h1>お問い合わせのご確認。</h1>
        <h3><span class="marker"><%= @inquiry.name %>様、</span>お問い合わせいただきありがとうございました。</h3>
        <p>土日を除く、３日営業日以内に返信致します。よろしくお願いたします。</p>
    </div>
  </div>
</main>